// vue/start-login/src/App.vue
<script setup lang="ts">
import { onUnmounted, ref } from 'vue'
import { IdvIntegrationService, type IdvMessageEvent } from '@regulaforensics/idv-capture-web'
import { FaceIdv } from '@regulaforensics/idv-face'
import { DocumentIdv } from '@regulaforensics/idv-document'

const service = ref<IdvIntegrationService | null>(null)
const isOpen = ref(false)

const listener = (event: IdvMessageEvent) => {
  console.log(event)
}

const startLogin = async () => {
  const loginConfig = {
    applicationId: "", // set application id
    baseUrl: "" , // set base url
    metadata: {
      additionalProp1: {},
    },
    locale: 'en',
  }

  service.value = new IdvIntegrationService()
  service.value.sessionRestoreMode = true
  service.value.eventListener = listener

  const initResult = await service.value.initialize({
    modulesConfig: {
      docreader: {
        devLicense: 'Base64License',
      },
    },
    includedModules: [FaceIdv, DocumentIdv],
  })

  if (initResult?.error) {
    console.log(initResult.error)
    return
  }

  isOpen.value = true

  const startLoginResult = await service.value.startLogin(loginConfig)
  console.log(startLoginResult)

  isOpen.value = false
}

onUnmounted(() => {
  service.value?.deinitialize()
})
</script>

<template>
  <div class="wrapper">
    <button v-if="!isOpen" class="button" @click="startLogin">Start Login</button>
    <div v-else class="container">
      <idv-flow></idv-flow>
    </div>
  </div>
</template>

<style scoped>
.wrapper {
  display: flex;
  height: 100%;
  width: 100%;
  justify-content: center;
  align-items: center;
}

.container {
  display: flex;
  position: absolute;
  height: 100%;
  width: 100%;
  top: 0;
  left: 0;
  justify-content: center;
  align-items: center;
}

.button {
  padding: 10px 30px;
  color: white;
  font-size: 16px;
  border-radius: 2px;
  background-color: #bd7dff;
  border: 1px solid #bd7dff;
  cursor: pointer;
}
</style>

// react-ts/start-login/App.tsx
import { useRef, useState} from "react";
import { IdvIntegrationService, IdvMessageEvent } from "@regulaforensics/idv-capture-web";
import { FaceIdv } from "@regulaforensics/idv-face";
import { DocumentIdv } from "@regulaforensics/idv-document";
import styles from "./styles.module.css";

function App() {
  const service = useRef<IdvIntegrationService | null>(null);
  const [isOpen, setIsOpen] = useState(false);

  const listener = (event: IdvMessageEvent) => {
    console.log(event);
  }

  const startLogin = async() => {
    const loginConfig = {
      applicationId: "", // set application id
      baseUrl: "" , // set base url
      metadata: {
        additionalProp1: {},
      },
      locale: 'en'
    };

    service.current = new IdvIntegrationService();
    service.current.sessionRestoreMode = true;
    service.current.eventListener = listener;

    const initResult = await service.current?.initialize({
      modulesConfig: {
        docreader:
            {devLicense: 'Base64License'}
      },
      includedModules: [FaceIdv, DocumentIdv],
    });

    if (initResult?.error) {
      console.log(initResult.error);
      return;
    }

    setIsOpen(true);

    const startLoginResult = await service.current?.startLogin(loginConfig);
    console.log(startLoginResult);

    setIsOpen(false);
  }

  return (
    <div className={styles.wrapper}>
      <button className={styles.button} onClick={() => startLogin()}>Start Login</button>
      {isOpen && (
          <div className={styles.container}>
            <idv-flow></idv-flow>
          </div>
      )}
    </div>
  );
}

export default App;
