// react-ts/start-login/App.tsx
import { useRef, useState} from "react";
import { IdvIntegrationService, IdvMessageEvent } from "@regulaforensics/idv-capture-web";
import { FaceIdv } from "@regulaforensics/idv-face";
import { DocumentIdv } from "@regulaforensics/idv-document";
import styles from "./styles.module.css";

function App() {
  const service = useRef<IdvIntegrationService | null>(null);
  const [isOpen, setIsOpen] = useState(false);

  const listener = (event: IdvMessageEvent) => {
    console.log(event);
  }

  const startLogin = async() => {
    const loginConfig = {
      applicationId: "", // set application id
      baseUrl: "" , // set base url
      metadata: {
        additionalProp1: {},
      },
      locale: 'en'
    };

    service.current = new IdvIntegrationService();
    service.current.sessionRestoreMode = true;
    service.current.eventListener = listener;

    const initResult = await service.current?.initialize({
      modulesConfig: {
        docreader:
            {devLicense: 'Base64License'}
      },
      includedModules: [FaceIdv, DocumentIdv],
    });

    if (initResult?.error) {
      console.log(initResult.error);
      return;
    }

    setIsOpen(true);

    const startLoginResult = await service.current?.startLogin(loginConfig);
    console.log(startLoginResult);

    setIsOpen(false);
  }

  return (
    <div className={styles.wrapper}>
      <button className={styles.button} onClick={() => startLogin()}>Start Login</button>
      {isOpen && (
          <div className={styles.container}>
            <idv-flow></idv-flow>
          </div>
      )}
    </div>
  );
}

export default App;

// angular/start-login/src/app/app.ts
import { Component, OnDestroy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IdvComponent } from './components/idv.component';
import { IdvIntegrationService, IdvMessageEvent } from '@regulaforensics/idv-capture-web';
import { FaceIdv } from '@regulaforensics/idv-face';
import { DocumentIdv } from '@regulaforensics/idv-document';

@Component({
  selector: 'app-root',
  imports: [CommonModule, IdvComponent],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements OnDestroy {
  isOpen = signal(false);
  service: IdvIntegrationService | null = null;

  listener = (event: IdvMessageEvent) => {
    console.log(event);
  };

  async startLogin() {
    const loginConfig = {
      applicationId: "", // set application id
      baseUrl: "" , // set base url
      metadata: {
        additionalProp1: {},
      },
      locale: 'en',
    };

    this.service = new IdvIntegrationService();
    this.service.sessionRestoreMode = true;
    this.service.eventListener = this.listener;

    const initResult = await this.service.initialize({
      modulesConfig: {
        docreader: {
          devLicense: 'Base64License',
        },
      },
      includedModules: [FaceIdv, DocumentIdv],
    });

    if (initResult?.error) {
      console.log(initResult.error);
      return;
    }

    this.isOpen.set(true);

    const startLoginResult = await this.service.startLogin(loginConfig);
    console.log(startLoginResult);

    this.isOpen.set(false);
  }

  ngOnDestroy() {
    this.service?.deinitialize();
  }
}
